### ISSUE TITLE
is it dying ?

### ISSUE THREAD

**Issue by xieyuheng** [scheme/edwin48#1]
any clean-up and hacking notes to help dev-ers ?

**Comment by roderyc** [comment]
@xieyuheng is there something specific you'd like to know? There are some notes in https://github.com/scheme/edwin48/tree/master/docs

**Comment by xieyuheng** [comment]
I wish to join in the development
but I can not even build it ::

  ~/play/edwin48 master
    git submodule init
Submodule 'pantene' (git://a-chinaman.com/pantene) registered for path 'pantene'
Submodule 'soosy' (git://a-chinaman.com/soosy) registered for path 'soosy'
Submodule 'terminfo' (git://a-chinaman.com/terminfo) registered for path 'terminfo'

  ~/play/edwin48 master
    git submodule update
Cloning into 'pantene'...
fatal: unable to connect to a-chinaman.com:
a-chinaman.com[0: 64.22.124.146]: errno=Connection refused

Clone of 'git://a-chinaman.com/pantene' into submodule path 'pantene' failed

1  ~/play/edwin48 master*

**Comment by xieyuheng** [comment]
could you please add the submodules into https://github.com/scheme/
or just into https://github.com/scheme/edwin48/
:)

**Comment by roderyc** [comment]
@xieyuheng updated the links for pantene and terminfo, and digging up the soosy code now. sorry about that!

**Comment by roderyc** [comment]
@xieyuheng soosy's submodule reference is fixed as well now. I've also updated the Readme with some pointers that might get you started. Hope that helps.
